---
driver:
  name: vagrant
  customize:
    memory: 4096

transport:
  name: winrm
  elevated: true

provisioner:
  name: chef_zero
  log_file: c:\chef\chef-client.log
  # log_level: debug
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: win_2012

suites:
  - name: default
    run_list:
      - recipe[directory_sync::test]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
